# Use a Golang base image
FROM golang:1.17-alpine
# Set the working directory to /app
WORKDIR /assignment3
# Copy the necessary files from your project to the Docker image
COPY cmd/ ./cmd/
COPY pkg/ ./pkg/
COPY controller/ ./controller/
COPY db/ ./db/
COPY routes/ ./routes/
COPY main/ ./main/
COPY models/ ./models/
COPY go.mod .
COPY go.sum .
# Install necessary dependencies
RUN apk add --no-cache git && \
    go get -u gorm.io/driver/postgres && \    
    go get -u gorm.io/gorm && \
    go mod tidy
# Build the project and specify the output binary file
RUN go build -o assignment3 ./cmd/main.go
# Set the entry point for the Docker image
CMD ["./assignment3"] 